name: CoffeeJournal
options:
  bundleIdPrefix: com.pranavski
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "15.0"

targets:
  CoffeeJournal:
    type: application
    platform: iOS
    sources:
      - CoffeeJournal
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pranavski.CoffeeJournal
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_GENERATION_MODE: GeneratedFile
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_NSCameraUsageDescription: "CoffeeJournal needs camera access to take photos of your drinks"
        INFOPLIST_KEY_NSPhotoLibraryUsageDescription: "CoffeeJournal needs photo library access to save and select drink photos"
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
